### ISSUE TITLE
NPE in PMDRuleVisitor.visit(ArrayCreationExpr)

### ISSUE THREAD

**Issue by cal101** [walkmod/walkmod-pmd-plugin#13]
It is possible that "n.getDimensions() != null" is false but initializer is not set via constructor
```
    public ArrayCreationExpr(int beginLine, int beginColumn, int endLine, int endColumn, Type type,
            List<Expression> dimensions, int arrayCount) {
```

~~I tried 1,5h to produce a test case. Giving up.
Seems to be related to~~

```
           final String[] x = new String[]{
                    "y",
                    "z." + s,
                    ""};

```

Reproducable test case: https://github.com/cal101/walkmod-misc/tree/pmd-plugin-tests

**Comment by rpau** [comment]
Fixed and deployed.
