### ISSUE TITLE
new pmd refactorings: braces 

### ISSUE THREAD

**Issue by cal101** [walkmod/walkmod-pmd-plugin#16]
https://pmd.github.io/pmd-5.5.5/pmd-java/rules/java/braces.html

contained in #14 as https://github.com/walkmod/walkmod-pmd-plugin/pull/14/commits/7a8d0536b4449d264040e945f03abd508772fff5

**Comment by cal101** [comment]
Hi @rpau!

Would the chances of accepting my pull request grow when extracting the working parts and enhancements from the bug examples?

Cal

**Comment by rpau** [comment]
Yes, of course :)

**Comment by cal101** [comment]
Extracted change, see pull request.

**Comment by cal101** [comment]
Merged.
